<a href="https://colab.research.google.com/github/salmanromeo/ECEN_5513_Stochastic_Systems/blob/main/Gaussian_random_vector_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#####$Y$ is a Gaussian random vector with mean $[1,2,3,4,5]^T$ and covariance $[4,2,2,2,2;2,4,2,2,2;2,2,4,2,2;2,2,2,4,2;2,2,2,2,4]$.

#####Write a code to generate a large number of samples of $Y$ and calculate the sample mean and sample covariance. Compare with the true mean and covariance.

In [3]:
import numpy as np

# Define the true mean and covariance
true_mean = np.array([1, 2, 3, 4, 5])
true_covariance = np.array([[4, 2, 2, 2, 2],
                             [2, 4, 2, 2, 2],
                             [2, 2, 4, 2, 2],
                             [2, 2, 2, 4, 2],
                             [2, 2, 2, 2, 4]])

# Number of samples to generate
num_samples = 100000

# Generate independent samples from a standard Gaussian distribution
independent_samples = np.random.randn(5, num_samples)

# Apply linear transformation to get samples following the desired distribution
chol_decomposition = np.linalg.cholesky(true_covariance)
samples = np.dot(chol_decomposition, independent_samples) + true_mean.reshape(-1, 1)

# Calculate sample mean and sample covariance
sample_mean = np.mean(samples, axis=1)
sample_covariance = np.cov(samples)

# Print the results
print("True Mean:\n", true_mean)
print("Sample Mean:\n", sample_mean)
print("True Covariance:\n", true_covariance)
print("Sample Covariance:\n", sample_covariance)

True Mean:
 [1 2 3 4 5]
Sample Mean:
 [0.99825499 2.00075602 2.99851958 4.01348339 4.99812093]
True Covariance:
 [[4 2 2 2 2]
 [2 4 2 2 2]
 [2 2 4 2 2]
 [2 2 2 4 2]
 [2 2 2 2 4]]
Sample Covariance:
 [[4.01384769 2.01664649 2.01956155 2.03050265 2.02160771]
 [2.01664649 3.99845766 1.99067203 2.00331186 2.00804755]
 [2.01956155 1.99067203 3.98901837 2.01619342 2.0075958 ]
 [2.03050265 2.00331186 2.01619342 4.02983101 2.02557168]
 [2.02160771 2.00804755 2.0075958  2.02557168 4.00757767]]
