<a href="https://colab.research.google.com/github/salmanromeo/ECEN_5513_Stochastic_Systems/blob/main/Gaussian_random_vector_generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#####$Y$ is a Gaussian random vector with mean $[1,2,3,4,5]^T$ and covariance $[4,2,2,2,2;2,4,2,2,2;2,2,4,2,2;2,2,2,4,2;2,2,2,2,4]$.

#####Write a code to generate a large number of samples of $Y$ and calculate the sample mean and sample covariance. Compare with the true mean and covariance.

In [1]:
import numpy as np

# True mean and covariance matrix
true_mean = np.array([1, 2, 3, 4, 5])
true_covariance = np.array([[4, 2, 2, 2, 2],
                             [2, 4, 2, 2, 2],
                             [2, 2, 4, 2, 2],
                             [2, 2, 2, 4, 2],
                             [2, 2, 2, 2, 4]])

# Number of samples to generate
num_samples = 10000

# Generate samples of Y
samples = np.random.multivariate_normal(true_mean, true_covariance, num_samples)

# Calculate sample mean and sample covariance
sample_mean = np.mean(samples, axis=0)
sample_covariance = np.cov(samples, rowvar=False)  # rowvar=False ensures columns are treated as variables

# Print the results
print("True Mean:")
print(true_mean)

print("\nTrue Covariance Matrix:")
print(true_covariance)

print("\nSample Mean:")
print(sample_mean)

print("\nSample Covariance Matrix:")
print(sample_covariance)

True Mean:
[1 2 3 4 5]

True Covariance Matrix:
[[4 2 2 2 2]
 [2 4 2 2 2]
 [2 2 4 2 2]
 [2 2 2 4 2]
 [2 2 2 2 4]]

Sample Mean:
[1.01732322 2.02066775 3.01960147 4.01242875 5.01077431]

Sample Covariance Matrix:
[[4.02871118 1.99522475 2.00244584 2.04084642 1.99342184]
 [1.99522475 3.94979769 1.96838274 1.98027402 1.97749324]
 [2.00244584 1.96838274 4.01620543 2.03732188 2.00393085]
 [2.04084642 1.98027402 2.03732188 4.04955724 2.01344764]
 [1.99342184 1.97749324 2.00393085 2.01344764 4.05045826]]
